services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    environment:
      - CLUSTER_NAME=atbd-netflix
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./docker/hadoop:/etc/hadoop
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      - ./docker/hadoop:/etc/hadoop
    networks:
      - hadoop

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: >
      bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/data
    networks:
      - bigdata-net

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/data
    networks:
      - bigdata-net

  dask-scheduler:
    image: daskdev/dask:latest
    container_name: dask-scheduler
    command: ["dask-scheduler", "--port", "8786"]
    volumes:
      - ./dask:/opt/dask-apps
      - ./data:/data
    ports:
      - "8787:8787"
    networks:
      - bigdata-net

  dask-worker:
    image: daskdev/dask:latest
    container_name: dask-worker
    command: ["dask-worker", "tcp://dask-scheduler:8786"]
    depends_on:
      - dask-scheduler
    volumes:
      - ./dask:/opt/dask-apps
      - ./data:/data
    networks:
      - bigdata-net

networks:
  hadoop:
  bigdata-net:

volumes:
  hadoop_namenode:
  hadoop_datanode1: